language: node_js
script: npm test
node_js:
- node
- io.js
- '0.12'
notifications:
  email: false
before_install:
- git fetch origin master:master
- git fetch origin branch-for-testing:branch-for-testing
deploy:
  provider: npm
  email: npm@eli-white.com
  api_key:
    secure: I0WjgrsIskIL9MSS+h27t3Twztyo2afLK6g7btVWcle4b4At0bOpoUzjSVx8mXojdle6X3PkxJc0D4QwOHHtNIYeGdyU0mgRBapN7ECdPZrZmoowM9VqVvyzZDe7E6Pp1lgEMwPeNAyTmZo+3FeCiwIlWPQ0Y2AyAeYNEMaAs5YQx6Bz6VoIBCma1Ee+8HIaky/fxZsXFHad+VTuqu4RZuRBSkxZcPwaZaL8qyERlx+WMupvdwFm50qm8KUU+QoDCRAMjAMO0kgCrRd9rTmoTAo6AbeEx93ibJMVaSg/vjc/1Cokvnts0foSzGdeLAOmwnps+S+AodOgUo/jnryiBbjhzdqoFcxVmr0BMDZZf3fNfk/PtzIsK+IT75NwraFZqRsA5LWNuYUl/+Wc0/G5g6Ze1VPBYnMiWg1182RsdNzuf4YZXgKsYyocNycsjzGLT2MSKPmTfIcz38mzoEXF9icQQY8N9U1tt6z7IhOrABX65L8RlLUE2kNjkq4gZNG8edrSTXrWVIcO2r31hDUkh85M5xEf7OHPX1IoPlqJq1q9Bh5AZUbCQ8a5nL1w8zNfYzrk+1Nd2Ibnl7CAalYBR6OXLRkknFFPGraMr3vF6P7s6S1KVcwA6qDFcGNfPuUb8OzYrvXPVaPq1lbC/I6MSJ92mG8AIUZdu7KnczdAtKA=
  on:
    tags: true
    repo: TheSavior/git-common-ancestor
    node: node